name: Demo Pipeline #Worflow name

on: push #trigger

jobs: 
  test:
    runs-on: ubuntu-latest #runner
    steps:
      - name: Hello World Command
        run: echo "Hello World!" > demo.txt
        # use run to execute shell commands directly on the runner
      - run: cat demo.txt
        # add default github variables like GITHUB_REPOSITORY, GITHUB_SHA, GITHUB_REF etc.
      - name: Show GitHub Context 
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Event Name: ${{ github.event_name }}"
      - name: List all files in the current directory
        run: ls -al
        
      - name: Checkout code
        uses: actions/checkout@v6.0.2
     
      - name: List all files in the repository
        run: ls -al
 
